feat(linux): iniciar suporte da aplicacao para Linux

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,20 +2,20 @@
 
 branch="$(git rev-parse --abbrev-ref HEAD)"
 if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
-  if [ "$ALLOW_MAIN_COMMIT" != "1" ]; then
-    echo "You can't commit directly to $branch"
-    echo "To bypass this check, run: $env:ALLOW_MAIN_COMMIT=1; git commit -m \"your message\""
-    exit 1
-  else
-    echo "WARNING: Bypassing branch protection for $branch"
-  fi
+    if [ "$ALLOW_MAIN_COMMIT" != "1" ]; then
+        echo "You can't commit directly to $branch"
+        echo "To bypass this check, run: ALLOW_MAIN_COMMIT=1 git commit -m \"your message\""
+        exit 1
+    else
+        echo "WARNING: Bypassing branch protection for $branch"
+    fi
 fi
 
 # Check if branch starts with "beta/" and bypass lint-staged
 case "$branch" in
-  beta/*)
-    echo "Beta branch detected ($branch) - skipping lint-staged"
-    exit 0
+    beta/*)
+        echo "Beta branch detected ($branch) - skipping lint-staged"
+        exit 0
     ;;
 esac
 
